name: memorize_scripture
description: A spaced repetition based scripture memory app
publish_to: 'none'
version: 2.3.0+27

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_svg_plus: ^2.0.13+1
  get_it: ^9.0.5
  http: ^1.2.2
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pocketbase: ^0.23.0
  scrollable_positioned_list: ^0.3.8
  settings_ui: ^2.0.2
  share_plus: ^12.0.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3
  url_launcher: ^6.3.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg