name: memorize_scripture
description: A spaced repetition based scripture memory app
publish_to: 'none'
version: 2.3.0+27

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  flutter_svg_plus: ^2.0.13+1
  get_it: ^9.0.5
  http: ^1.2.2
  package_info_plus: ^9.0.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pocketbase: ^0.23.0
  scrollable_positioned_list: ^0.3.8
  settings_ui: ^2.0.2
  share_plus: ^12.0.1
  shared_preferences: ^2.3.2
  sqflite: ^2.3.3
  url_launcher: ^6.3.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.24.9
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg

flutter_native_splash:
  # 1. Customize the parameters below.
  # 2. run the following command in the terminal:
  # dart run flutter_native_splash:create

  android: true
  ios: false
  web: false
  
  #! Background color for all platforms except Android 12+:
  color: "#f7f0e2"
  color_dark: "#28271e"

  # general image for all platform (except android 12+):
  # allows you to specify an image used in the splash screen. It must be a
  # png file and should be sized for 4x pixel density.
  image:                assets/splash_light_640.png
  image_dark:           assets/splash_dark_640.png

  # hide notice bar on android. ios already hides it by default. 
  # Has no effect in web since web has no notification bar.
  fullscreen: true                # default false

  #! ANDROID 12+ configuration:
  android_12:
    # background color
    color: "#f7f0e2"
    color_dark: "#28271e"

    # center-logo
    # If this parameter is not specified, the app's launcher icon will be used instead. 
    # Please note that the splash screen will be clipped to a circle on the center of the screen. 
    # with background: 960×960 px (fit within circle 640px in diameter)    
    # without background: 1152×1152 px (fit within circle 768px in diameter)
    # ensure that the most important design elements of your image are placed within a circular area 
    image: assets/splash_light_1152.png
    image_dark: assets/splash_dark_1152.png

    # center-logo background color
    # icon_background_color: "#f7f0e2"
    # icon_background_color_dark: "#28271e"